// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/about-hero/BoldAsymmetric.tsx": () => import("../components/mockups/about-hero/BoldAsymmetric.tsx"),
  "./components/mockups/about-hero/Centered.tsx": () => import("../components/mockups/about-hero/Centered.tsx"),
  "./components/mockups/about-hero/SplitStats.tsx": () => import("../components/mockups/about-hero/SplitStats.tsx")
};
